spring:
    datasource:    
        url: jdbc:postgres://${DATABASE_HOST:localhost}:${DATABASE_PORT:3307}/${DATABASE_NAME:test}
        password: ${DATABASE_PASSWORD:1234}
        username: ${DATABASE_USERNAME:root}



