
# Name the action itself
name: CI to docker hub
#Set the event when this should be done and the branches it should work on
on:
  push:
    branches: ["master"]
# Specify exactly what is to be done to accomplish this action and in what environment it should be executed
jobs:
  build:
    runs-on: ubuntu-latest
    # What are the steps to be followed in order to make this work
    steps:
    # Checkout a repo action enables the workflow to access the repository
      - name: Checkout to our repo
        uses: actions/checkout@v3
      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{secrets.DOCKER_HUB_USERNAME}}
          password: ${{secrets.DOCKER_HUB_ACCESS_TOKEN}}
      - name: Set up docker buildx
        id: buildx
        uses: docker/setup-buildx-action@v1
        with:
          version: v0.7.0
      - name: docker build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with: 
          context: ./
          file: ./Dockerfile
          push: true
          tags: ${{secrets.DOCKER_HUB_USERNAME}}/firstboot:latest
      - name: Image digest 
        run: echo ${{steps.docker_build.output.digest}}
          
      
        
