name: CI to heroku

on:
  push:
    branches: ["master"]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Build, push and deploy docker container to heroku
        uses: gonuit/heroku-docker-deploy@v1.3.3
        with: 
          email: ${{secrets.HEROKU_EMAIL}}
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: ${{secrets.HEROKU_APPNAME}}
          docker_file_directory: ./
          docker_file_name: Dockerfile
          process_type: web
